version: "3.1"

services:
  mariadb:
    image: mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: projecte
      MYSQL_DATABASE: phpmyadmin
    ports:
      - 3306:3306
    volumes:
      - ./docker/mariadb-data:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      - PMA_HOST=mariadb
      - PMA_USER=root
      - PMA_PASSWORD=projecte
      - UPLOAD_LIMIT=50M
    ports:
      - 8081:80
    depends_on:
      - mariadb
